name: Build and Deploy for Github Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 #

      - name: Install Dependencies
        run: npm ci

      - name: Build Renderer
        run: npm run build:renderer 

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: packages/renderer/dist

  deploy:
    needs: build

    permissions:
      pages: write      
      id-token: write  

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 